import "./globals.css"
import type { ReactNode } from "react"
import Providers from "@/components/providers/session-provider"
import { Toaster } from "@/components/ui/toaster"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
